# --- ETAPA 1: Dependencias ---
FROM node:22-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

# --- ETAPA 2: Builder ---
FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_APP_VERSION
ENV NEXT_PUBLIC_APP_VERSION=$NEXT_PUBLIC_APP_VERSION

ARG NEXT_PUBLIC_ENABLE_INTEGRATIONS
ENV NEXT_PUBLIC_ENABLE_INTEGRATIONS=$NEXT_PUBLIC_ENABLE_INTEGRATIONS

ARG NEXT_PUBLIC_ENABLE_BILLING
ENV NEXT_PUBLIC_ENABLE_BILLING=$NEXT_PUBLIC_ENABLE_BILLING

ARG NEXT_PUBLIC_ENABLE_PWA
ENV NEXT_PUBLIC_ENABLE_PWA=$NEXT_PUBLIC_ENABLE_PWA

ARG NEXT_PUBLIC_ENABLE_WALKTHROUGH
ENV NEXT_PUBLIC_ENABLE_WALKTHROUGH=$NEXT_PUBLIC_ENABLE_WALKTHROUGH

ARG NEXT_PUBLIC_ENABLE_SCREEN_LOCK
ENV NEXT_PUBLIC_ENABLE_SCREEN_LOCK=$NEXT_PUBLIC_ENABLE_SCREEN_LOCK

ARG NEXT_PUBLIC_ENABLE_OFFLINE
ENV NEXT_PUBLIC_ENABLE_OFFLINE=$NEXT_PUBLIC_ENABLE_OFFLINE

ARG NEXT_PUBLIC_ENABLE_AI_CHAT
ENV NEXT_PUBLIC_ENABLE_AI_CHAT=$NEXT_PUBLIC_ENABLE_AI_CHAT

RUN npx prisma generate
RUN npm run build

# --- ETAPA 3: Runner (Optimizado) ---
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN apk add --no-cache wget libc6-compat

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone/node_modules ./node_modules
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

COPY --from=builder --chown=nextjs:nodejs /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/@prisma/client ./node_modules/@prisma/client
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/bcryptjs ./node_modules/bcryptjs
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma

USER nextjs

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

EXPOSE 3000

CMD ["node", "server.js"]
